import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import NavigationDropdown from "@/components/NavigationDropdown";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex min-h-screen flex-col">
          <header className="border-b bg-white/70 backdrop-blur dark:bg-black/40">
            <div className="relative mx-auto flex max-w-5xl items-center justify-between px-4 py-4">
              <Link href="/" className="flex items-center gap-2">
                <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-gradient-to-br from-blue-500 to-blue-600 text-white shadow-md">
                  <span className="text-xl font-bold">T</span>
                </div>
                <span className="text-2xl font-bold tracking-tight text-zinc-900 dark:text-zinc-50">
                  threadsail
                </span>
              </Link>
              <nav className="absolute left-1/2 flex -translate-x-1/2 items-center gap-2">
                <NavigationDropdown
                  label="Solutions"
                  items={[
                    { label: "EDU Recycling", href: "/solutions/edurecycling" },
                    { label: "Library Check Out", href: "/solutions/librarycheckout" },
                    { label: "Student Devices", href: "/solutions/studentdevices" },
                  ]}
                />
                <Link
                  href="/pricing"
                  className="flex items-center gap-1 rounded-md px-4 py-2 text-sm font-medium text-zinc-700 transition-colors hover:bg-zinc-100 dark:text-zinc-300 dark:hover:bg-zinc-800"
                >
                  Pricing
                </Link>
                <NavigationDropdown
                  label="Info"
                  items={[
                    { label: "About", href: "/info/about" },
                    { label: "Contact", href: "/info/contact" },
                    { label: "Support", href: "/info/support" },
                  ]}
                />
              </nav>
              <Link
                href="/dashboard"
                className="rounded-md bg-blue-600 px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-blue-700"
              >
                Sign In
              </Link>
            </div>
          </header>

          <main className="mx-auto flex w-full max-w-5xl flex-1 px-4 py-8">
            {children}
          </main>

          <footer className="border-t text-center text-sm text-white">
            <div className="mx-auto max-w-5xl px-4 py-4">
              © 2026 threadsail. Built with Next.js & Cursor.
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
